steps:
  # Fetch submodules
  - name: "gcr.io/cloud-builders/git"
    args: ["submodule", "update", "--init", "--recursive"]
  # Build the server Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/mmorpg-server"
      - -f
      - "./server/Dockerfile"
      - "."
  # Push the server Docker image to the GCR
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/$PROJECT_ID/mmorpg-server"
  # Deploy everything to the GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kube.yaml
      - --image=gcr.io/$PROJECT_ID/mmorpg-server
      - --location=europe-north1
      - --cluster=mmorpg-dev
      - --timeout=20m0s
timeout: 1600s
