steps:
  # Deploy everything to the GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kube.yaml
      - --location=europe-north1
      - --cluster=mmorpg-dev
    timeout: 1600s
