steps:
  # Build the server Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "mmorpg-server"
      - -f
      - "./server/Dockerfile"
      - "."
  # Deploy everything to the GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kube.yaml
      - --location=europe-north1
      - --cluster=mmorpg-dev
timeout: 1600s
images: ["mmorpg-server"]
