steps:
  # Fetch submodules
  - name: "gcr.io/cloud-builders/git"
    args: ["submodule", "update", "--init", "--recursive"]
  # Fetch the latest server Docker image from the GCR
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/mmorpg-server:latest || exit 0"]
  # Build the server Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/mmorpg-server"
      - -f
      - "./server/Dockerfile"
      - --cache-from
      - "gcr.io/$PROJECT_ID/mmorpg-server:latest"
      - "."
  # Push the server Docker image to the GCR
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/$PROJECT_ID/mmorpg-server"
  # Deploy database to the GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kube-db.yaml
      - --location=europe-north1
      - --cluster=mmorpg-dev
      - --timeout=10m0s
  # Deploy server to the GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kube-server.yaml
      - --image=gcr.io/$PROJECT_ID/mmorpg-server
      - --location=europe-north1
      - --cluster=mmorpg-dev
      - --timeout=15m0s
