steps:
  # Fetch submodules
  - name: "gcr.io/cloud-builders/git"
    args: ["submodule", "update", "--init", "--recursive"]
  # Build the server Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/mmorpg-server:latest"
      - -f
      - "./server/Dockerfile"
      - "."
  # Push the server Docker image to the GCR
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/$PROJECT_ID/mmorpg-server:latest"
  # Deploy database to the GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kube-db.yaml
      - --location=europe-north1
      - --cluster=mmorpg-dev
  # Deploy server to the GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kube-server.yaml
      - --image=gcr.io/$PROJECT_ID/mmorpg-server:latest
      - --location=europe-north1
      - --cluster=mmorpg-dev
