/*
 * The map reader is responsibe for reading the generated map assets on runtime. Map assets are generated by the loader.
 */
#pragma once

#include <iostream>
#include <fstream>
#include <vector>
#include <sstream>

/*
 * Reads a matrix from a text file. Values should be separated by commas and rows by newlines.
 *
 * Row sizes do not need to match.
 */
void readMatrixFromFile(std::vector<std::vector<std::string>> &matrix, std::string filepath)
{
  std::ifstream file(filepath);
  std::string line;

  if (!file.is_open())
  {
    throw std::runtime_error("Error reading matrix from file: " + filepath + ". File could not be opened.");
  }

  while (std::getline(file, line))
  {
    std::vector<std::string> row;
    std::stringstream ss(line);
    std::string cell;

    while (std::getline(ss, cell, ','))
    {
      row.push_back(cell);
    }

    matrix.push_back(row);
  }

  file.close();
}

void loadAccessMap(std::vector<std::vector<uint8_t>> &accessMap, std::string path)
{
  std::vector<std::vector<std::string>> accessMapString;
  readMatrixFromFile(accessMapString, path);

  for (auto &row : accessMapString)
  {
    std::vector<uint8_t> rowUint8;
    for (auto &col : row)
    {
      rowUint8.push_back(std::stoi(col));
    }
    accessMap.push_back(rowUint8);
  }
}