var hierarchy =
[
    [ "AABB", "structAABB.html", null ],
    [ "Action", "classAction.html", [
      [ "AttackAction", "classAttackAction.html", null ],
      [ "MoveAction", "classMoveAction.html", null ],
      [ "ObjectInteractAction", "classObjectInteractAction.html", null ],
      [ "RespawnAction", "classRespawnAction.html", null ]
    ] ],
    [ "AllocatedBuffer", "structAllocatedBuffer.html", null ],
    [ "AllocatedImage", "structAllocatedImage.html", null ],
    [ "Animation", "structAnimation.html", null ],
    [ "AnimationConfig", "structAnimationConfig.html", null ],
    [ "AnimationNode", "structAnimationNode.html", null ],
    [ "AreaObject", "structAreaObject.html", null ],
    [ "AssetCache", "classAssetCache.html", null ],
    [ "AssetManager", "classAssetManager.html", null ],
    [ "BoneNode", "structBoneNode.html", null ],
    [ "CallBackTimer", "structCallBackTimer.html", null ],
    [ "Camera", "classCamera.html", null ],
    [ "CharacterAnimationData", "structCharacterAnimationData.html", null ],
    [ "CharacterAssetData", "structCharacterAssetData.html", null ],
    [ "CharacterData", "structCharacterData.html", null ],
    [ "CharacterObject", "structCharacterObject.html", null ],
    [ "CharacterObjectUniformBuffer", "structCharacterObjectUniformBuffer.html", null ],
    [ "CharacterVertex", "structCharacterVertex.html", null ],
    [ "Client", "classClient.html", null ],
    [ "CombinedImage", "structCombinedImage.html", null ],
    [ "GraphicsObjectManager::CommandUnit", "structGraphicsObjectManager_1_1CommandUnit.html", null ],
    [ "Coordinates", "structCoordinates.html", null ],
    [ "DatabaseManager", "classDatabaseManager.html", null ],
    [ "DescriptorBuilder", "classDescriptorBuilder.html", null ],
    [ "DescriptorSetLayoutCache::DescriptorLayoutHasher", "structDescriptorSetLayoutCache_1_1DescriptorLayoutHasher.html", null ],
    [ "DescriptorSetLayoutCache", "classDescriptorSetLayoutCache.html", null ],
    [ "DescriptorSetLayoutCache::DescriptorSetLayoutInfo", "structDescriptorSetLayoutCache_1_1DescriptorSetLayoutInfo.html", null ],
    [ "DrawableObject", "structDrawableObject.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "Entity", "classEntity.html", [
        [ "Npc", "classNpc.html", [
          [ "AggressiveNpc", "classAggressiveNpc.html", null ],
          [ "PassiveNpc", "classPassiveNpc.html", null ]
        ] ],
        [ "PlayerCharacter", "classPlayerCharacter.html", null ]
      ] ],
      [ "EquippableItem", "classEquippableItem.html", null ]
    ] ],
    [ "EngineStatistics", "structEngineStatistics.html", null ],
    [ "Equipment", "classEquipment.html", null ],
    [ "GameCharacters", "structGameCharacters.html", null ],
    [ "GameItems", "structGameItems.html", null ],
    [ "GameObject", "structGameObject.html", null ],
    [ "GameObjects", "structGameObjects.html", null ],
    [ "GameObjectUniformBuffer", "structGameObjectUniformBuffer.html", null ],
    [ "GameSkill", "structGameSkill.html", null ],
    [ "GameWorld", "classGameWorld.html", null ],
    [ "GeneralItemStruct", "structGeneralItemStruct.html", [
      [ "EquippableItemStruct", "structEquippableItemStruct.html", null ],
      [ "FoodItemStruct", "structFoodItemStruct.html", null ]
    ] ],
    [ "GeneralObjectStruct", "structGeneralObjectStruct.html", [
      [ "LootObjectStruct", "structLootObjectStruct.html", null ],
      [ "ResourceObjectStruct", "structResourceObjectStruct.html", null ]
    ] ],
    [ "GfxOrientation", "structGfxOrientation.html", null ],
    [ "GraphicsObjectManager", "classGraphicsObjectManager.html", null ],
    [ "Hit", "structHit.html", null ],
    [ "ImageData", "structImageData.html", null ],
    [ "Inventory", "classInventory.html", null ],
    [ "Item", "classItem.html", [
      [ "EquippableItem", "classEquippableItem.html", null ],
      [ "FoodItem", "classFoodItem.html", null ]
    ] ],
    [ "ItemAssetData", "structItemAssetData.html", null ],
    [ "ItemStats", "structItemStats.html", null ],
    [ "ItemTransform", "structItemTransform.html", null ],
    [ "Map", "classMap.html", null ],
    [ "MapAABBData", "structMapAABBData.html", null ],
    [ "MapAreaAssetData", "structMapAreaAssetData.html", null ],
    [ "Node", "structNode.html", null ],
    [ "nodeCompare", "structnodeCompare.html", null ],
    [ "NPCData", "structNPCData.html", null ],
    [ "Object", "classObject.html", [
      [ "LootObject", "classLootObject.html", null ],
      [ "ResourceObject", "classResourceObject.html", null ]
    ] ],
    [ "ObjectAssetData", "structObjectAssetData.html", null ],
    [ "ObjectLocation", "structObjectLocation.html", null ],
    [ "ObjectWithFileinfo", "structObjectWithFileinfo.html", null ],
    [ "PlayerData", "structPlayerData.html", null ],
    [ "PlayerTable", "structPlayerTable.html", null ],
    [ "PoolManager", "classPoolManager.html", null ],
    [ "QueueFamilyIndices", "structQueueFamilyIndices.html", null ],
    [ "RehtiGraphics", "classRehtiGraphics.html", null ],
    [ "RehtiGui", "classRehtiGui.html", null ],
    [ "Server", "classServer.html", null ],
    [ "SimpleMesh", "classSimpleMesh.html", null ],
    [ "SimpleVertex", "structSimpleVertex.html", null ],
    [ "SkillInfo", "structSkillInfo.html", null ],
    [ "SkillSet", "classSkillSet.html", null ],
    [ "SpawnCoordinateBounds", "structSpawnCoordinateBounds.html", null ],
    [ "SwapChainSupportDetails", "structSwapChainSupportDetails.html", null ],
    [ "Target", "structTarget.html", null ],
    [ "TestObject", "structTestObject.html", null ],
    [ "TestObjectUniformBuffer", "structTestObjectUniformBuffer.html", null ],
    [ "TimerCallbackSystem", "classTimerCallbackSystem.html", null ],
    [ "Vertex", "structVertex.html", null ],
    [ "YieldableItem", "structYieldableItem.html", null ],
    [ "YieldableItems", "structYieldableItems.html", null ]
];