#pragma once

/*
 * The map reader is responsibe for reading the generated map assets on runtime. Map assets are generated by the loader.
 */

#include <vector>

void loadAccessMap(std::vector<std::vector<uint8_t>> &accessMap, std::string path);