#pragma once

/**
 * @file The map reader is responsibe for reading the generated map assets on runtime. Map assets are generated by the loader.
 */

#include <vector>
#include <string>

/**
 * @brief Loads the access map from the given path.
 * @param accessMap Empty matrix of uint8_t that will be filled with the access map information.
 * @param path to the access map file.
 */
void loadAccessMap(std::vector<std::vector<uint8_t>> &accessMap, std::string path);

/**
 * @brief Loads the height map from the given path.
 * @param heightMap Empty matrix of int that will be filled with the height map information.
 * @param path to the height map file.
 */
void loadHeightMap(std::vector<std::vector<int>> &heightMap, std::string path);

/**
 * @brief Loads the area map from the given path.
 * @param areaMap Empty matrix of string that will be filled with the area map information.
 * @param path to the area map file.
 */
void loadAreaMap(std::vector<std::vector<std::string>> &areaMap, std::string path);