name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - chore/docs
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  Generate-Doxygen-Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Generate doxygen
        run: doxygen docs/Doxyfile

      - name: Create jekyll
        run: touch ./nojekyll

      - name: Add Doxygen Awesome CSS as submodule
        run: git submodule add https://github.com/jothepro/doxygen-awesome-css.git

      - name: Add dotcomb as submodule
        run: git submodule add https://github.com/Makistos/dotcomb.git

      - name: generate image
        run: python3 dotcomb/dotcomb.py --output collaboration-graph.png

      - name: commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generate doxygen docs :rocket:"
          git push
