name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - chore/docs
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs
          branch: gh-pages
          config_file: docs/Doxyfile
