name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - chore/docs
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add Doxygen Awesome CSS as submodule
        run: git submodule add https://github.com/jothepro/doxygen-awesome-css.git

      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: .
          target_folder: .
          branch: gh-pages
          config_file: docs/Doxyfile
